### ISSUE TITLE
Seeding Database and Mock Data

### ISSUE THREAD

**Issue by mdwiltfong** [hazeltonbw/ecommerce-backend#7]
At the moment [this PR](https://github.com/hazeltonbw/ecommerce-backend/pull/6) and the tests for products, users, etc are not in sync. It would be best to provide mock data that can be used in unit tests as well as manual testing.

**Comment by hazeltonbw** [comment]
Hi Michael, please check the pull request: https://github.com/hazeltonbw/ecommerce-backend/pull/6
I have updated and added mock data, database seeding, database setup, and all tests are currently passing :) 
Please check it out and let me know if there are any other additions needed. Thanks!

**Comment by hazeltonbw** [comment]
Hi @mdwiltfong, please check the pull request: https://github.com/hazeltonbw/ecommerce-backend/pull/10
I have updated and added mock data, database seeding, database setup, and all tests are currently passing! :) 
Please check it out and let me know if there are any other additions needed. Thanks!

**Comment by mdwiltfong** [comment]
Hey @hazeltonbw ! Thanks for following up. I really liked how you implemented `pg-promise`. This package really did stream line seeding the database. 

I'm a little confused though, because when looking at `package.json` I was expecting `seedDatabase.js` to create data for manual testing when i run `npm run seed-db`. Instead it left the tables empty. I believe this is because in the context of `npm run seed-db` JS doesn't execute the anonymous async function.  

Also, the function does work when executing `npm run tests`, but it doesn't do any tear down. As a result the tests tend to fail after running them a second time. In order to resolve this you'll have to implement some sort of function that clears the mock data.

**Comment by hazeltonbw** [comment]
Hey Michael! Thanks for getting back so soon. I originally was going to just have the seed-db script do all the seeding for me, but thought that it would be better if the seeding was done in the tests, since that's where it'll be used. 
I will fix seedDatabase.js so that it works with the script, this was an oversight when creating the anonymous async function. 
It's weird that the second time running the tests they fail, since seedDatabase() clears all of the tables in the database before doing anything else. I'll have to take a closer look at this. Thanks!

**Comment by mdwiltfong** [comment]
What's odder is that as a I re-run the tests, eventually they all pass. I tried clearing out some tables to see if I can reproduce this, but I can't. Did you notice this too?

**Comment by hazeltonbw** [comment]
> What's odder is that as a I re-run the tests, eventually they all pass. I tried clearing out some tables to see if I can reproduce this, but I can't. Did you notice this too?

Yes, it really is strange. I will have to put this on the back-burner for now as I have exhausted all of my knowledge on troubleshooting databases & testing frameworks. I hope to meet at the JS support hour and hopefully figure this out though!
